// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: settings/linearchannel/linearchannel.proto

package linearchannel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinearChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code        string                   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name        string                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName string                   `protobuf:"bytes,4,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Platforms   []*LinearChannelPlatform `protobuf:"bytes,5,rep,name=platforms,proto3" json:"platforms,omitempty"`
}

func (x *LinearChannel) Reset() {
	*x = LinearChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settings_linearchannel_linearchannel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinearChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearChannel) ProtoMessage() {}

func (x *LinearChannel) ProtoReflect() protoreflect.Message {
	mi := &file_settings_linearchannel_linearchannel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinearChannel.ProtoReflect.Descriptor instead.
func (*LinearChannel) Descriptor() ([]byte, []int) {
	return file_settings_linearchannel_linearchannel_proto_rawDescGZIP(), []int{0}
}

func (x *LinearChannel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LinearChannel) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LinearChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinearChannel) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LinearChannel) GetPlatforms() []*LinearChannelPlatform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type LinearChannelPlatform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlatformId  int64 `protobuf:"varint,1,opt,name=platformId,proto3" json:"platformId,omitempty"`
	TerritoryId int64 `protobuf:"varint,2,opt,name=territoryId,proto3" json:"territoryId,omitempty"`
	OfferTypeId int64 `protobuf:"varint,3,opt,name=offerTypeId,proto3" json:"offerTypeId,omitempty"`
}

func (x *LinearChannelPlatform) Reset() {
	*x = LinearChannelPlatform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settings_linearchannel_linearchannel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinearChannelPlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearChannelPlatform) ProtoMessage() {}

func (x *LinearChannelPlatform) ProtoReflect() protoreflect.Message {
	mi := &file_settings_linearchannel_linearchannel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinearChannelPlatform.ProtoReflect.Descriptor instead.
func (*LinearChannelPlatform) Descriptor() ([]byte, []int) {
	return file_settings_linearchannel_linearchannel_proto_rawDescGZIP(), []int{1}
}

func (x *LinearChannelPlatform) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *LinearChannelPlatform) GetTerritoryId() int64 {
	if x != nil {
		return x.TerritoryId
	}
	return 0
}

func (x *LinearChannelPlatform) GetOfferTypeId() int64 {
	if x != nil {
		return x.OfferTypeId
	}
	return 0
}

var File_settings_linearchannel_linearchannel_proto protoreflect.FileDescriptor

var file_settings_linearchannel_linearchannel_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x6c, 0x69, 0x6e, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2a, 0x63, 0x6f,
	0x6d, 0x2e, 0x69, 0x6e, 0x62, 0x63, 0x75, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0xca, 0x01, 0x0a, 0x0d, 0x4c, 0x69, 0x6e,
	0x65, 0x61, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x5f, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x6e,
	0x62, 0x63, 0x75, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x73, 0x22, 0x7b, 0x0a, 0x15, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x74, 0x65, 0x72, 0x72, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x65, 0x72, 0x72, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x49, 0x64, 0x42, 0x52, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x4e, 0x42, 0x43, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x2f, 0x67, 0x76,
	0x73, 0x2d, 0x6d, 0x73, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x6c, 0x69, 0x6e, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x3b, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_settings_linearchannel_linearchannel_proto_rawDescOnce sync.Once
	file_settings_linearchannel_linearchannel_proto_rawDescData = file_settings_linearchannel_linearchannel_proto_rawDesc
)

func file_settings_linearchannel_linearchannel_proto_rawDescGZIP() []byte {
	file_settings_linearchannel_linearchannel_proto_rawDescOnce.Do(func() {
		file_settings_linearchannel_linearchannel_proto_rawDescData = protoimpl.X.CompressGZIP(file_settings_linearchannel_linearchannel_proto_rawDescData)
	})
	return file_settings_linearchannel_linearchannel_proto_rawDescData
}

var file_settings_linearchannel_linearchannel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_settings_linearchannel_linearchannel_proto_goTypes = []interface{}{
	(*LinearChannel)(nil),         // 0: com.inbcu.rpc.types.settings.linearchannel.LinearChannel
	(*LinearChannelPlatform)(nil), // 1: com.inbcu.rpc.types.settings.linearchannel.LinearChannelPlatform
}
var file_settings_linearchannel_linearchannel_proto_depIdxs = []int32{
	1, // 0: com.inbcu.rpc.types.settings.linearchannel.LinearChannel.platforms:type_name -> com.inbcu.rpc.types.settings.linearchannel.LinearChannelPlatform
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_settings_linearchannel_linearchannel_proto_init() }
func file_settings_linearchannel_linearchannel_proto_init() {
	if File_settings_linearchannel_linearchannel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_settings_linearchannel_linearchannel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinearChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_settings_linearchannel_linearchannel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinearChannelPlatform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_settings_linearchannel_linearchannel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_settings_linearchannel_linearchannel_proto_goTypes,
		DependencyIndexes: file_settings_linearchannel_linearchannel_proto_depIdxs,
		MessageInfos:      file_settings_linearchannel_linearchannel_proto_msgTypes,
	}.Build()
	File_settings_linearchannel_linearchannel_proto = out.File
	file_settings_linearchannel_linearchannel_proto_rawDesc = nil
	file_settings_linearchannel_linearchannel_proto_goTypes = nil
	file_settings_linearchannel_linearchannel_proto_depIdxs = nil
}
